services:
  api:
    # For GPU support, use one of:
    image: localai/localai:latest-gpu-nvidia-cuda-13

    pull_policy: missing
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 5m
      retries: 5
    ports:
      - 127.0.0.1:8090:8080
    environment:
      - DEBUG=true
    volumes:
    - /storage/shortstack/localai/models:/models:cached
    - /storage/shortstack/localai/backends:/backends:cached

    # For NVIDIA GPUs with standalone Docker:
    devices:
      - nvidia.com/gpu=all