# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
        ##### Storage
        ## Hard drives
        # Yarrow
        ./modules/hardware/storage/yarrow.nix

        # Orchid
        ./modules/hardware/storage/orchid.nix

        # Nettle
        ./modules/hardware/storage/nettle.nix
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/745867b1-4e74-440b-b378-25b6bbb484e6";
      fsType = "ext4";
    };

# In ~/Lodestone/hosts/island/hardware-configuration.nix
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4A39-7CF4"; 
    fsType = "vfat";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4a2799a1-8b55-41b2-ba67-8082fe858f85"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
